# -*- coding: utf-8 -*-
"""Copy of tensor-demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I7d6oIaDt54ml1EsyB2wgI_foRs6Rkc_
"""

import pandas as pd

import numpy as np

df=pd.read_csv('/content/placement.csv')

df.head()

df.shape

"""1)preprocessing+eda+feature selection

"""

df=df.iloc[:,1:]

df.head

df.head()

import matplotlib.pyplot as plt

plt.scatter(df['cgpa'],df['iq'])

plt.scatter(df['cgpa'],df['iq'],c=df['placement'])



"""extracting input and output coloumns

"""

x=df.iloc[:,0:2]
y=df.iloc[:,-1]

df.head

df.head()

x

y

y.shape

x.shape

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1)

# that means that 10percent data ka hi test honga baaki 90 training main jayege

x_train

y_train

x_test

# //sklearn se again preprocessing karenge

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

x_train=scaler.fit_transform(x_train)

x_train

x_test=scaler.transform(x_test)

#Model training honga ab yaha se

from sklearn.linear_model import LogisticRegression

clf=LogisticRegression()

#model training
clf.fit(x_train,y_train)

#evaluation main directly accuracy nikalenge on test model
y_predict=clf.predict(x_test)

x_test

y_test

from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_predict)

from mlxtend.plotting import plot_decision_regions

plot_decision_regions(x_train, y_train.values, clf=clf, legend=2)

import pickle

pickle.dump(clf,open('model.pkl','wb'))

